"""Added update date to wallet

Revision ID: 0f7b2d042621
Revises: 4bbefb27fd81
Create Date: 2024-12-28 19:20:38.880868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f7b2d042621'
down_revision: Union[str, None] = '4bbefb27fd81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wallet', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wallet', 'updated_at')
    # ### end Alembic commands ###
