"""Creating first tables

Revision ID: 67939c9a8eac
Revises: 
Create Date: 2025-01-02 12:16:19.278464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '67939c9a8eac'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('status', sa.String(), nullable=False),
                    sa.Column('triggered_by', sa.Integer(), nullable=False),
                    sa.Column('task_name', sa.String(), nullable=True),
                    sa.Column('details', sa.String(), nullable=True),
                    sa.Column('created_date', sa.DateTime(), nullable=True),
                    sa.Column('updated_date', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('user',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('email', sa.String(), nullable=False),
                    sa.Column('password_hash', sa.String(), nullable=False),
                    sa.Column('verified', sa.Boolean(), nullable=False),
                    sa.Column('active', sa.Boolean(), nullable=False),
                    sa.Column('role', sa.String(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_table('account_removal_request',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('user_id', sa.UUID(), nullable=False),
                    sa.Column('request_timestamp', sa.DateTime(), nullable=True),
                    sa.Column('status', sa.String(), nullable=False),
                    sa.Column('details', sa.JSON(), nullable=True),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_account_removal_request_id'), 'account_removal_request', ['id'], unique=False)
    op.create_table('wallet',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('user_id', sa.UUID(), nullable=False),
                    sa.Column('balance', sa.Float(), nullable=True),
                    sa.Column('currency', sa.String(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_wallet_currency'), 'wallet', ['currency'], unique=False)
    op.create_index(op.f('ix_wallet_id'), 'wallet', ['id'], unique=False)
    op.create_index(op.f('ix_wallet_user_id'), 'wallet', ['user_id'], unique=False)
    op.create_table('transaction',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('wallet_id', sa.UUID(), nullable=False),
                    sa.Column('type', sa.String(), nullable=False),
                    sa.Column('amount', sa.Float(), nullable=False),
                    sa.Column('category', sa.String(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['wallet_id'], ['wallet.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_transaction_id'), 'transaction', ['id'], unique=False)
    op.create_index(op.f('ix_transaction_wallet_id'), 'transaction', ['wallet_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transaction_wallet_id'), table_name='transaction')
    op.drop_index(op.f('ix_transaction_id'), table_name='transaction')
    op.drop_table('transaction')
    op.drop_index(op.f('ix_wallet_user_id'), table_name='wallet')
    op.drop_index(op.f('ix_wallet_id'), table_name='wallet')
    op.drop_index(op.f('ix_wallet_currency'), table_name='wallet')
    op.drop_table('wallet')
    op.drop_index(op.f('ix_account_removal_request_id'), table_name='account_removal_request')
    op.drop_table('account_removal_request')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('task')
    # ### end Alembic commands ###
