"""Changed details column from json to str

Revision ID: 7b313d98d94d
Revises: 67939c9a8eac
Create Date: 2025-01-02 12:51:31.303401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7b313d98d94d'
down_revision: Union[str, None] = '67939c9a8eac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('account_removal_request', 'details',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=sa.String(length=100),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('account_removal_request', 'details',
               existing_type=sa.String(length=100),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    # ### end Alembic commands ###
