"""Added table for tracking account removal requests

Revision ID: 88c28aceabce
Revises: d170c548d477
Create Date: 2025-01-02 09:58:02.633185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '88c28aceabce'
down_revision: Union[str, None] = 'd170c548d477'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_removal_request',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('user_id', sa.UUID(), nullable=False),
                    sa.Column('request_timestamp', sa.DateTime(), nullable=True),
                    sa.Column('status', sa.String(), nullable=False),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_account_removal_request_id'), 'account_removal_request', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_account_removal_request_id'), table_name='account_removal_request')
    op.drop_table('account_removal_request')
    # ### end Alembic commands ###
