"""Added cascade deletes

Revision ID: 9555466c4834
Revises: 1320099096ba
Create Date: 2024-12-29 17:38:48.793419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9555466c4834'
down_revision: Union[str, None] = '1320099096ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('transaction_wallet_id_fkey', 'transaction', type_='foreignkey')
    op.create_foreign_key(None, 'transaction', 'wallet', ['wallet_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('wallet_user_id_fkey', 'wallet', type_='foreignkey')
    op.create_foreign_key(None, 'wallet', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wallet', type_='foreignkey')
    op.create_foreign_key('wallet_user_id_fkey', 'wallet', 'user', ['user_id'], ['id'])
    op.drop_constraint(None, 'transaction', type_='foreignkey')
    op.create_foreign_key('transaction_wallet_id_fkey', 'transaction', 'wallet', ['wallet_id'], ['id'])
    # ### end Alembic commands ###
